### ISSUE TITLE
no instance of function template "std::_Invoker_ret<_Rx, false>::_Call [with _Rx=pbrt::Float]" matches the argument list

### ISSUE THREAD

**Issue by lsysyem** [mmp/pbrt-v4#84] opened 2020-11-15 13:25 UTC
use vs 2019 
optix 7.1
cuda 11.0

**Comment by povmaniaco** [comment] 2020-11-15 16:52
> 
> 
> use vs 2019
> optix 7.1
> cuda 11.0

You can provide more info about this error? I can't find this code.
Cheers..

**Comment by lsysyem** [comment] 2020-11-16 04:47
![QAIGR}NEW5$IO8FR}OPPXGK](https://user-images.githubusercontent.com/22446403/99213934-e3681d00-2809-11eb-80e2-d430466f2b32.png)

**Comment by lsysyem** [comment] 2020-11-16 04:48
> > 使用 vs 2019  optix 7.1  cuda 11.0
> 
> 您可以提供有关此错误的详细信息吗？我找不到此代码。
> 干杯。

![QAIGR}NEW5$IO8FR}OPPXGK](https://user-images.githubusercontent.com/22446403/99213983-fd096480-2809-11eb-96d0-44a8c6becdf9.png)

**Comment by safes** [comment] 2020-11-16 09:21
I  meet the same Issue, I find the first parameter of  the Image::Array2D<Float> GetSamplingDistribution(
        std::function<Float (const Point2f&)> dxdA = [](const Point2f&)->Float { return Float(1); },
        const Bounds2f &domain = Bounds2f(Point2f(0, 0), Point2f(1, 1)),
        Allocator alloc = {});   raise this issue .   Anyone has any idea to solve it ?

**Comment by pbrt4bounty** [comment] 2020-11-16 14:10
I can't reproduce here.. even in Debug or Release mode. Have you modify some code related Image class??

**Comment by lsysyem** [comment] 2020-11-16 14:17
> I can't reproduce here.. even in Debug or Release mode. Have you modify some code related Image class??

![$K3$4SA7UQMO(0D0WI064J1](https://user-images.githubusercontent.com/22446403/99262376-dcb4c680-2858-11eb-8f0b-4bc9a309a021.png)
only this;   and  debug release is the same result;
and i update to cuda11.1, optix7.2, vs2019 16.9 preview1.0,win10 SDK 18362.0;
the error is same.

**Comment by pierremoreau** [comment] 2020-11-16 17:10
I can confirm the issue with the latest master on VS 2019 16.9 preview 1.0, CUDA 11.1, OptiX 7.2
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29515\include\functional(947): error : no instance of function template "std::_Invoker_ret<_Rx, false>::_Call [with _Rx=pbrt::Float]" matches the argument list
              argument types are: (std::decay_t<std::remove_reference_t<lambda [](pbrt::Point2f)->pbrt::Float &>>, pbrt::Point2f)
            detected during:
              instantiation of "_Rx std::_Func_impl_no_alloc<_Callable, _Rx, _Types...>::_Do_call(_Types &&...) [with _Callable=std::decay_t<std::remove_reference_t<lambda [](pbrt::Point2f)->pbrt::Float &>>, _Rx=pbrt::Float, _Types=<pbrt::Point2f>]" 
  (923): here
              instantiation of "std::_Func_impl_no_alloc<_Callable, _Rx, _Types...>::_Func_impl_no_alloc(_Other &&) [with _Callable=std::decay_t<std::remove_reference_t<lambda [](pbrt::Point2f)->pbrt::Float &>>, _Rx=pbrt::Float, _Types=<pbrt::Point2f>, _Other=std::remove_reference_t<lambda [](pbrt::Point2f)->pbrt::Float &>, <unnamed>=0]" 
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29515\include\xmemory(239): here
              instantiation of "_Ty *std::_Global_new<_Ty,_Types...>(_Types &&...) [with _Ty=std::_Func_impl_no_alloc<std::decay_t<std::remove_reference_t<lambda [](pbrt::Point2f)->pbrt::Float &>>, pbrt::Float, pbrt::Point2f>, _Types=<std::remove_reference_t<lambda [](pbrt::Point2f)->pbrt::Float &>>]" 
  (1039): here
              instantiation of "void std::_Func_class<_Ret, _Types...>::_Reset(_Fx &&) [with _Ret=pbrt::Float, _Types=<pbrt::Point2f>, _Fx=std::remove_reference_t<lambda [](pbrt::Point2f)->pbrt::Float &>]" 
  (1170): here
              instantiation of "std::function<_Fty>::function(_Fx) [with _Fty=pbrt::Float (pbrt::Point2f), _Fx=lambda [](pbrt::Point2f)->pbrt::Float, <unnamed>=int]" 
  D:\Softwares\pbrt-v4\src\pbrt/util/image.h(329): here
  
  1 error detected in the compilation of "D:/Softwares/pbrt-v4/src/pbrt/lights.cpp".
```

I have tried digging around a bit, see if passing a `(const Point2f &p) -> Float` instead of a `(Point2f) -> Float` could have been the issue, but no luck.

**Comment by lyd405121** [comment] 2020-11-23 03:22
I also met this compile error since I update the vs2019 to the lastest version
Before the update of vs2019 everything works well

**Comment by mmp** [comment] 2020-11-24 00:51
Weird. This seems like a regression in vs2019. Does changing that method declaration in `util/image.h` to something like this fix the problem? I'm hoping that removing the lambda function as a default value for a std::function parameter might be a simplification that the compiler needs.

```
    Array2D<Float> GetSamplingDistribution(
        std::function<Float(Point2f)> dxdA,
        const Bounds2f &domain = Bounds2f(Point2f(0, 0), Point2f(1, 1)),
        Allocator alloc = {});
    Array2D<Float> GetSamplingDistribution() {
        auto dxdA = [](Point2f) { return Float(1); };
        return GetSamplingDistribution(dxdA);
    }
```

(@lyd405121 some of the methods in lights.cpp are compiled for the GPU, but not all of them, but the whole thing has to be compiled by nvcc. This particular method is one that is CPU-only..)

**Comment by pierremoreau** [comment] 2020-11-24 09:02
I still got the same error with that sample. Doing the following solved some compilation errors (but would not be a proper fix in any way) but the call to `Array2D<Float> d = image.GetSamplingDistribution(dwdA, screenBounds);` (lights.cpp:232) still generated that same error nevertheless.
```c++
    Array2D<Float> GetSamplingDistribution(
        std::function<Float(Point2f)> dxdA,
        const Bounds2f &domain = Bounds2f(Point2f(0, 0), Point2f(1, 1)),
        Allocator alloc = {});
    Array2D<Float> GetSamplingDistribution() {
         std::function<Float(Point2f)> dxdA;
        return GetSamplingDistribution(dxdA);
    }
```

**Comment by safes** [comment] 2020-11-24 10:00
I do not think  get to work any way with  std::function. Haha.

**Comment by safes** [comment] 2020-11-24 14:35
I update a the  GetSamplingDistribution(...) to a template function:

template<typename callable>
    Array2D<Float> GetSamplingDistribution(
        callable dxdA = [](Point2f) { return Float(1); }
        ,const Bounds2f &domain = Bounds2f(Point2f(0, 0), Point2f(1, 1))
        ,Allocator alloc = {}) 
    {
        Array2D<Float> dist(resolution[0], resolution[1], alloc);
        ParallelFor(0, resolution[1], [&](int64_t y0, int64_t y1) {
            for (int y = y0; y < y1; ++y) {
                for (int x = 0; x < resolution[0]; ++x) {
                    // This is noticably better than MaxValue: discuss / show
                    // example..
                    Float value = GetChannels({x, y}).Average();

                    // Assume jacobian term is basically constant over the
                    // region.
                    Point2f p = domain.Lerp(
                        Point2f((x + .5f) / resolution[0], (y + .5f) / resolution[1]));
                    dist(x, y) = value * dxdA(p);
                }
            }
        });
        return dist;
    }

It seems  get to work.  Great.

**Comment by safes** [comment] 2020-11-24 14:38
I update a the GetSamplingDistribution(...) to a template function:
    template<typename callable>
    Array2D<Float> GetSamplingDistribution(
        callable dxdA = [](Point2f) { return Float(1); }
        ,const Bounds2f &domain = Bounds2f(Point2f(0, 0), Point2f(1, 1))
        ,Allocator alloc = {}) 
    {
     ....
    }

**Comment by safes** [comment] 2020-11-24 14:43
I change the function to a template  function , and it seems to get to work . 

'template< typename callable >
    Array2D <Float> GetSamplingDistribution(
        callable dxdA = [](Point2f) { return Float(1); }
        ,const Bounds2f &domain = Bounds2f(Point2f(0, 0), Point2f(1, 1))
        ,Allocator alloc = {}) 
    {  .... }'

**Comment by lsysyem** [comment] 2020-11-26 01:21
> I change the function to a template function , and it seems to get to work .
> 
> 'template< typename callable >
> Array2D GetSamplingDistribution(
> callable dxdA = { return Float(1); }
> ,const Bounds2f &domain = Bounds2f(Point2f(0, 0), Point2f(1, 1))
> ,Allocator alloc = {})
> { .... }'

it not't works for me!

**Comment by povmaniaco** [comment] 2020-11-26 09:33
I need review here, but the last changes are break my build's, both with cuda or without

**Comment by mmp** [comment] 2021-01-01 23:02
I've pushed a fix (I hope) following @safes's suggestion. (Let me know if that does it and sorry for the delay..)

**Comment by lyd405121** [comment] 2021-01-05 08:16
> I've pushed a fix (I hope) following @safes's suggestion. (Let me know if that does it and sorry for the delay..)

wow。That works！！！！！

**Comment by lsysyem** [comment] 2021-01-05 09:42
> 根据他的建议， 我提出了一个@safes（我希望） 。（让我知道， 如果这样做， 并很抱歉的延误。

wow。That works！！！！！..thanks!!!!!!

**Closed** 2021-01-05 09:46 UTC
