### ISSUE TITLE
Reproducibility of volpath

### ISSUE THREAD

**Issue by webanck** [mmp/pbrt-v4#85] opened 2020-11-19 17:05 UTC
I observed differences between renders of the same scene across two different machines.
I found some pieces of code with undefined behaviors, mainly caused by calls of the type `RNG(sampler.Get1D(), sampler.Get1D())`.
I tracked and corrected those I found but it was still not enough.
Differences in floating point operations still occured when sampling lights, resulting in total different hashs for the remaining part of the path.

All those problem happened when compiling with gcc-7.5 and gcc-9.3, I tried both on both machines.
Then, I compiled with clang++-10 and all renders were the same, even without my corrections.

Are you concerned about reproducibility ? Have you experienced the same kind of issue with gcc ?
I saw that the Murmur hashing isn't portable between little- and big-endians but from my tests, the floating point operations are the first source of discrepancies.

**Comment by mmp** [comment] 2020-11-19 18:54
It's a good question. In general, I think it's most important that runs be deterministic on the same system and that, I believe is the case, save for integrators that splat samples into the film like the bidirectional ones which may come out differently if multiple threads splat to the same pixel but in different orders over different runs (but that doesn't apply to volpath.)

As far as on different systems / different compilers, most computations should come out the same, but I would be suspicious that there might be some differences due to different precision in the evaluation of the trigonometric / other transcendental functions in the standard library. (And those are indeed used in light sampling, for some lights at least.) My guess is that would be why you're seeing differences, but I'd be curious to know what the actual root cause is, if you end up digging further.

**Comment by webanck** [comment] 2020-11-22 09:03
I went a little further and compared the CPU flags enabled when compiling with gcc in native arch (`-march=native`) with the command `gcc --help=target -march=native -mtune=native -Q`. Between my two computers, one has a skylake CPU whereas the other has a ivybridge one. The more recent skylake architecture enables extra instructions sets with the parameters:
```
-march=skylake 
-mmovbe 
-mabm 
-mfma
-mbmi
-mbmi2 
-mavx2
-mlzcnt
-mrdseed
-mprfchw -madx
-mclflushopt -mxsavec -mxsaves
-mtune=skylake
```

Now, the culprit for the differences was the `-mfma` option enabling fused multiply–add instructions. Rendering with PBRT compiled with gcc options `-O3 -march=native -mno-fma` finally produced the same output on both computers!

By the way, I checked again without the modifications of my pull request #86 but with the right gcc options, and the renders differed, so both are necessary to assure reproducibility on my side with gcc.
If you want to check on your computers, here are my renders of the Disney cloud scene with 1 sample per pixel (random sampler instead of sobol):
![rsampler-no-fma](https://user-images.githubusercontent.com/6747237/99898984-244ab080-2ca6-11eb-8ca7-6d52f34af0e6.png)
*The reproducible one with both pull request modifications and -no-fma*

![-mno-fma](https://user-images.githubusercontent.com/6747237/99898996-3debf800-2ca6-11eb-9b29-ea08df355efe.png)
*Only using option `-mno-fma`*

![rsampler](https://user-images.githubusercontent.com/6747237/99899383-4db90b80-2ca9-11eb-9a93-68968f51c18f.png)
*Only using pull request modifications*

![Vanilla](https://user-images.githubusercontent.com/6747237/99899388-57427380-2ca9-11eb-8b55-1e6077ca2020.png)
*Vanilla PBRT*





Fun fact: my laptop CPU is a i7 8550U 1.8GhZ (skylake from 2017) and my desktop CPU is a i7 3770k 3.5GHz (ivybridge from 2012), they both have 4 cores for 8 threads. Guess which one is faster on the same rendering? The one from my laptop which took 6 seconds to render instead of 13, but with way worse compilation time.

**Comment by mmp** [comment] 2020-11-24 00:44
That's quite interesting all around.  The Ivybridge is the last Intel CPU generation that doesn't have a hardware FMA instruction (it first came in with Haswell.) I had assumed that std::fma would give the same results on all systems, with or without an instruction for it, but apparently not.

I would be interested to hear if some of that performance difference is due to a slow emulation of FMA on the ivybridge system. It's not used *that* much in pbrt, but if it's slow enough, that could be part of it. (If you have a chance to replace the few uses of std::fma(a,b,c) with a*b+c and see how that affects performance, I'd be interested to hear.)

**Comment by mmp** [comment] 2020-11-24 00:45
(And if the perf. difference is significant, I could add some code to not use std::fma on systems where there isn't a hardware implementation of it...)

**Comment by webanck** [comment] 2020-11-24 10:06
@mmp Thanks for the merge!

The whole differences between the gcc native compilation options of the Skylake and Ivybridge architectures are:
```
-march=skylake 
-mmovbe 
-mabm 
-mfma
-mbmi
-mbmi2 
-mavx2
-mlzcnt
-mrdseed
-mprfchw -madx
-mclflushopt -mxsavec -mxsaves
-mtune=skylake
```
```
-march=ivybridge 
-mno-movbe 
-mno-abm 
-mno-fma
-mno-bmi
-mno-bmi2
-mno-avx2
-mno-lzcnt
-mno-rdseed
-mno-prfchw -mno-adx
-mno-clflushopt -mno-xsavec -mno-xsaves
-mtune=ivybridge
```

About performance, when rendering with disabled FMA on the Ivybridge CPU, I didn't notice any loss of speed. I also tried with the Ivybridge specific options disabled (thus using the same options as Skylake, namely `-O3 -march=native -mno-movbe -mno-abm -mno-fma -mno-bmi -mno-bmi2 -mno-avx2 -mno-lzcnt -mno-rdseed -mno-prfchw -mno-adx -mno-clflushopt -mno-xsavec -mno-xsaves`), again without any loss of speed.

For comparison, without any specific option, rendering with PBRT compiled with clang took 50 seconds on the laptop with Ivybridge CPU against 10 seconds on the desktop with Skylake CPU. The performance between PBRT compiled with clang or gcc is thus similar on the  Skylake CPU but ten times slower with clang on the Ivybridge.

About pure reproductibility, one other option that might be cumbersome would be the support of FMA4 instructions (`-mfma4`). According to wikipedia, it is supported by few AMD old CPUs but removed since Zen 1.

**Comment by webanck** [comment] 2020-11-24 11:25
Now on the use of `std::fma`, I replaced the associated calls in `util/float.h` and `util/sampling.h`, btw is there any good reason not to use the `FMA` wrapper from `float.h` in `sampling.h`?
From my tests, rendering is quicker without the `std::fma` on the Skylake CPU (6 seconds with both gcc and clang instead of 12 seconds) but it is similarly efficient on the Ivybridge with both gcc and clang.

**Comment by mmp** [comment] 2021-01-01 23:13
I just pushed a fix to get those `std::fma`s--thanks for pointing those out. Thanks also for chasing the rest of this down!

**Closed** 2021-01-01 23:13 UTC
