### ISSUE TITLE
nvcc fatal   : 'arch=native': expected a number

### ISSUE THREAD

**Issue by iscaswcm** [mmp/pbrt-v4#87] opened 2020-11-23 08:31 UTC
Platform:
Ubunutu 20.04 NVCC 11 Optix 7.2
After using cmake generates Makefile scripts,  when I comile pbrt v4 code,  nvcc gave a error message:
nvcc fatal   : 'arch=native': expected a number

After removing -march=native in ./CMakeFiles/pbrt_lib.dir/flags.make, it works.

CUDA_FLAGS =   -Xcudafe --diag_suppress=partial_override -Xcudafe --diag_suppress=virtual_function_decl_hidden -Xcudafe --diag_suppress=integer_sign_change -Xcudafe --diag_suppres    s=declared_but_not_referenced -Xcudafe --diag_suppress=implicit_return_from_non_void_function --expt-relaxed-constexpr --extended-lambda -Xnvlink -suppress-stack-size-warning --fo    rward-unknown-to-host-compiler --std=c++17 --use_fast_math -lineinfo -maxrregcount 128 --gpu-architecture=sm_75 -O3 -DNDEBUG   -D NDEBUG  -march=native

**Comment by varun19299** [comment] 2020-11-23 16:40
I got around this by commenting the following lines in the CMakeLists:

https://github.com/mmp/pbrt-v4/blob/67a4e928f7eb12f0aaedf78316bd05caee2021ff/CMakeLists.txt#L267

```
# TODO: how to specify this on windows?
check_cxx_compiler_flag ("-march=native" COMPILER_SUPPORTS_MARCH_NATIVE)
if (COMPILER_SUPPORTS_MARCH_NATIVE AND PBRT_BUILD_NATIVE_EXECUTABLE)
  list (APPEND PBRT_CXX_FLAGS -march=native)
endif ()
```

**Comment by varun19299** [comment] 2020-11-23 16:41
I think `nvcc` does not accept a `march` flag (unlike g++/clang).

**Comment by mmp** [comment] 2020-11-23 17:46
`nvcc` doesn't support `-march`, but this line in the CMakeLists file should pass it a flag that causes `nvcc` to pass it along to the host compiler for CPU code:
```
set (CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} --forward-unknown-to-host-compiler")
```

Looking at what @iscaswcm posted, it looks like there is a space between `--fo` and `ward-unknown-to-host-compiler`. I'm wondering if you may have inadvertently added a space to the `CMakeLists.txt` file?

(This error is otherwise especially surprising as that OS/compiler combination is exactly what I use, so should be the most safe at this point. :-) ).

**Comment by iscaswcm** [comment] 2020-11-24 03:34
@mmp  I just clone pbrt-v4 and make no changes to CMakeLists.txt file:

clone pbrt v4

$ mkdir build
$ cd build
$ make .. \
	-DPBRT_OPTIX7_PATH=/usr/local/NVIDIA-OptiX-SDK-7.1.0-linux64-x86_64
$ make -j16
Then I got such error.

**Comment by varun19299** [comment] 2020-11-24 03:34
Thank you for your reply. 

In my case, there was no space between `--fo` and `ward....`, i.e.,

```
CMAKE_CUDA_FLAGS = -Xcudafe --diag_suppress=partial_override -Xcudafe --diag_suppress=virtual_function_decl_hidden -Xcudafe --diag_suppress=integer_sign_change -Xcudafe --diag_suppress=declared_but_not_referenced -Xcudafe --diag_suppress=implicit_return_from_non_void_function --expt-relaxed-constexpr --extended-lambda -Xnvlink -suppress-stack-size-warning --forward-unknown-to-host-compiler --std=c++17 --use_fast_math -lineinfo -maxrregcount 128 --gpu-architecture=sm_61
```

(manually printed the variable). Yet, the issue with `march` persists.

**Comment by iscaswcm** [comment] 2020-11-24 07:32
Above all, if such a problem appears,  solutions are followings:
(1) rule out  check_cxx_compiler_flag ("-march=native" COMPILER_SUPPORTS_MARCH_NATIVE)
                    if (COMPILER_SUPPORTS_MARCH_NATIVE AND PBRT_BUILD_NATIVE_EXECUTABLE)
                         list (APPEND PBRT_CXX_FLAGS -march=native)
                    endif ()
thanks to varun19299 @varun19299
(2) After gemerating makefile scripts, remove -march=native flag in CMakeFiles/pbrt_lib.dir/flags.make file.

Special thanks to @mmp @varun19299

**Comment by mmp** [comment] 2020-11-25 14:48
Reopening since I still can't reproduce this myself and would like to keep `-march=native` in there if possible, since it adds a few percent speedup.

Could you provide a little more information? First, the versions of cmake and nvcc you've got? For me, it's
```
% nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:10:02_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0
% cmake --version
cmake version 3.16.3
```

Then, could you run make as `make -j16 VERBOSE=1` and attach the full output? Thanks!

**Comment by varun19299** [comment] 2020-11-25 16:20
Hi Matt,

nvcc version:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:38_PDT_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0
```

cmake version:
```
cmake version 3.18.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

Make logs [here](https://gist.github.com/varun19299/68b869ef95d3fc0a5b2c5716f2be6740).

**Comment by mmp** [comment] 2020-11-25 22:57
Thanks, Varun! I've done some more tests and can reproduce that with CUDA 11.0. (It's fine with CUDA 11.1--I'm not sure what the issue is...)

Unfortunately I haven't been able to figure out how to detect CUDA 11.0 vs 11.1 in the CMakeLists.file, so have just pushed a fix that disables it with CUDA builds. If you have a chance, if you could confirm whether top of tree builds directly now, that'd be fantastic.

**Comment by iscaswcm** [comment] 2020-11-26 06:47
Hi, Pharr! My cmake and nvcc information:


wcm@wcm-Precision:~$ cmake --version
cmake version 3.16.3


CMake suite maintained and supported by Kitware (kitware.com/cmake).
wcm@wcm-Precision:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:10:02_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0



OS: Ubuntu 20.04 Optix 7.1



Best Regards,
Changmao Wu
Lab. of Parallel Software and Computational Science
Institute of Software, Chinese Academy of Sciences
South 4 Street, Zhong Guan Cun, Haidian District, Beijing, China


Zipcode: 100190
---------------


致礼
吴长茂
北京市海淀区中关村南四街4号
中国科学院软件研究所
并行软件与计算科学实验室
邮编100190


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mmp/pbrt-v4"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月25日(星期三) 晚上10:48
收件人:&nbsp;"mmp/pbrt-v4"<pbrt-v4@noreply.github.com&gt;;
抄送:&nbsp;"吴长茂"<706627189@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [mmp/pbrt-v4] nvcc fatal   : 'arch=native': expected a number (#87)





 
Reopening since I still can't reproduce this myself and would like to keep -march=native in there if possible, since it adds a few percent speedup.
 
Could you provide a little more information? First, the versions of cmake and nvcc you've got? For me, it's
 % nvcc --version nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2020 NVIDIA Corporation Built on Tue_Sep_15_19:10:02_PDT_2020 Cuda compilation tools, release 11.1, V11.1.74 Build cuda_11.1.TC455_06.29069683_0 % cmake --version cmake version 3.16.3  
Then, could you run make as make -j16 VERBOSE=1 and attach the full output? Thanks!

**Comment by iscaswcm** [comment] 2020-11-26 06:51
Hi, Pharr! @mmp My cmake and nvcc information:

wcm@wcm-Precision:~$ cmake --version
cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
wcm@wcm-Precision:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:10:02_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0

OS: Ubuntu 20.04 Optix 7.1

**Comment by iscaswcm** [comment] 2020-11-26 07:13
@mmp,  It's so strange, this time compiling pbrt v4 is good even with -march=native since I update cuda from 11.0 to 11.1. The full output is here:(BTW, if you like, I will downgrade cuda to 11.0, and patste corresponding output.)

**Comment by varun19299** [comment] 2020-11-26 07:19
Unfortunately, I can't use CUDA 11.1, our cluster doesn't support it yet :(.

> Unfortunately I haven't been able to figure out how to detect CUDA 11.0 vs 11.1 in the CMakeLists.file, so have just pushed a fix that disables it with CUDA builds. If you have a chance, if you could confirm whether top of tree builds directly now, that'd be fantastic.

Sure, I'll try this. Does this mean that `-march=native` is disabled with CUDA builds?

**Comment by mmp** [comment] 2020-12-02 00:04
Yes--`-march=native` is disabled in that case now, unfortunately.

**Comment by varun19299** [comment] 2020-12-03 13:04
Yes, the build process works now (checked with latest commit, `62b393619160d90da93881c4929ee4ca268998cd`).

**Closed** 2020-12-04 00:12 UTC
