### ISSUE TITLE
Absolute 0 value in 'Dots' float texture causes a lot of NAN's and.. black dots.

### ISSUE THREAD

**Issue by pbrt4bounty** [mmp/pbrt-v4#283] opened 2022-06-29 18:06 UTC
Use a 0.00 value for "float outside" parameter causes a lots of nan's and black dots render result.
```
Texture "Dots_4723210491352" "float" "dots"
	"float inside" [ 0.99 ]
	"float outside" [ 0.00 ]
	"string mapping" [ "planar" ]
	"float udelta" [ 0.0 ]
	"float vdelta" [ 0.0 ]
	"vector3 v1" [ 1 0 0 ]
	"vector3 v2" [ 0 1 0 ]
Texture "Dots_4723210491352_scale" "float" "scale"
 	"float scale" [0.85]
	"texture tex" "Dots_4723210491352"

MakeNamedMaterial "Material.002"
	"string type" [ "coateddiffuse" ]
	"rgb reflectance" [ 0.8 0.8 0.8 ]
	"integer maxdepth" [ 10 ]
	"integer nsamples" [ 1 ]
	"bool remaproughness" [ true ]
	"texture uroughness" [ "Dots_4723210491352_scale" ]
	"float vroughness" [ 0.5 ]
	"float thickness" [ 0.10 ]
	"float eta" [ 1.5 ]
	"float g" [0.0]
	"rgb albedo" [ 0.8 0.8 0.8 ]
```
![black_dots](https://user-images.githubusercontent.com/73945652/176504374-8dcbdf7b-f6a7-44a1-bf27-2432bceef4a0.png)

A simple change from '0.00' to '0.00000000001'  fixes the error and produce a right render result.
Compiled and render under Windows 10.
There are the scene to check..
[dots.zip](https://github.com/mmp/pbrt-v4/files/9012974/dots.zip)

It would be helpful if someone else can confirm this, or maybe some other value is not set correctly.
Thanks!

**Comment by shadeops** [comment] 2022-06-29 18:54
You are running into a divide by zero here

https://github.com/mmp/pbrt-v4/blob/82f2356a179413523813875ab1d8d6f36e0813ea/src/pbrt/util/scattering.h#L118

**Comment by pbrt4bounty** [comment] 2022-06-29 19:21
Ohh 'TrowbridgeReitzDistribution' aka 'Oren-Nayar'. I remember a lot of issues with the glossy material and 'black-dots' in another render engine. :)

**Comment by pbrt4bounty** [comment] 2022-07-04 12:08
> You are running into a divide by zero here
> 
> https://github.com/mmp/pbrt-v4/blob/82f2356a179413523813875ab1d8d6f36e0813ea/src/pbrt/util/scattering.h#L118

Yes, this code divide with alpha_x and alpha_y but I can't see any control about by zero division for alpha_x and y.
I made an small test:
`Float e = tan2Theta * (Sqr(CosPhi(wm) / std::max(0.001f, alpha_x)) + Sqr(SinPhi(wm) / std::max(0.001f, alpha_y)));`
and seems that now I can't reproduce the black dots problem.
@mmp What's your opinion about it?
Cheers..

**Comment by pbrt4bounty** [comment] 2022-07-04 15:18
Ok. After a lot of tests(sometimes bad executed) the conclusion are this:
Using float instead texture :
```
"float uroughness" [ 0.0000000000000 ]
"float vroughness" [ 0.0000000000000 ]
``` 
Zero value is allowed without problems.
But when a combo float & texture is used, exists some limits for the float value
```
"texture uroughness" [ "dots_texture" ]
#"float vroughness" [ 0.000000000000000 ] #black dots
#"float vroughness" [ 0.000000000000001 ] #black dots
"float vroughness"  [ 0.00000000000001 ] #OK
```
As I said before, these limits can be easily defined in the part of the addon that creates the scene.
Btw.. all this test is done in a build with the option `PBRT_FLOAT_AS_DOUBLE` OFF
Better if anyone can confirm this cases, before to close this report.
Cheers..

**Comment by mmp** [comment] 2022-07-05 01:17
My guess is that a reasonable fix will be to apply a minimum non-zero roughness in the `TrowbridgeReitzDistribution` constructor if the other roughness is non-zero. (It may be reasonable to just fix `D()` to be robust to this edge case but there is also the need to review the other methods to see how they behave with one zero roughness and the other non-zero.) In any case, I haven't had a chance to look at this more closely and to confirm that fix doesn't introduce any other issues.

FWIW a pair of zero roughnesses leads to
```c++
    bool EffectivelySmooth() const { return std::max(alpha_x, alpha_y) < 1e-3f; }
```
returning true (which isn't the case necessarily with one being zero and the other bigger than 1e-3). In turn, code that uses `TrowbridgeReitzDistribution` mostly ignores it since the surface is sufficiently smooth.

**Comment by mmp** [comment] 2022-07-05 01:17
(And I'll try to look at this more closely tomorrow.)

**Comment by pbrt4bounty** [comment] 2022-07-05 12:04
Let me know if I can help you with some test here.

**Comment by mmp** [comment] 2022-07-05 13:50
Ok, this should be fixed now; confirmed that the dots.zip test case works. Let me know if you see any further issues!

**Closed** 2022-07-05 13:51 UTC

**Comment by pbrt4bounty** [comment] 2022-07-05 14:24
Can confirm that is also fixed here. Thanks a lot!
